from fastapi import APIRouter

from app.data import load_all
from app.utils import records

router = APIRouter(tags=["coaching"])


@router.get("/api/coaching")
def get_coaching_events(machine_id: str | None = None, severity: str | None = None):
    """Coaching tips generated by CAN-bus-style rules, newest first.
    Optional filters: by machine and/or severity (warning/critical/info,
    case-insensitive)."""
    events = load_all()["coaching_events"].copy()
    if events.empty:
        return []

    events = events.sort_values("Timestamp", ascending=False)

    if machine_id:
        events = events[events["Machine ID"] == machine_id]
    if severity:
        events = events[events["Severity"].str.lower() == severity.lower()]

    return records(events)
